# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'measurement.ui'
#
# Created: Fri Dec  6 19:31:53 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dlg_Measurement(object):
    def setupUi(self, Dlg_Measurement):
        Dlg_Measurement.setObjectName(_fromUtf8("Dlg_Measurement"))
        Dlg_Measurement.resize(806, 204)
        Dlg_Measurement.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(Dlg_Measurement)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(Dlg_Measurement)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Dlg_Measurement)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.lE_T_StabTime = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_T_StabTime.setObjectName(_fromUtf8("lE_T_StabTime"))
        self.gridLayout.addWidget(self.lE_T_StabTime, 2, 4, 1, 1)
        self.lE_M_MeasCurr = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_M_MeasCurr.setInputMask(_fromUtf8(""))
        self.lE_M_MeasCurr.setObjectName(_fromUtf8("lE_M_MeasCurr"))
        self.gridLayout.addWidget(self.lE_M_MeasCurr, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(Dlg_Measurement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.lE_T_HeatCurr = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_T_HeatCurr.setObjectName(_fromUtf8("lE_T_HeatCurr"))
        self.gridLayout.addWidget(self.lE_T_HeatCurr, 2, 1, 1, 1)
        self.lE_M_HeatCurr = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_M_HeatCurr.setObjectName(_fromUtf8("lE_M_HeatCurr"))
        self.gridLayout.addWidget(self.lE_M_HeatCurr, 1, 1, 1, 1)
        self.lE_M_StabTime = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_M_StabTime.setObjectName(_fromUtf8("lE_M_StabTime"))
        self.gridLayout.addWidget(self.lE_M_StabTime, 1, 4, 1, 1)
        self.lE_M_HeatTime = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_M_HeatTime.setObjectName(_fromUtf8("lE_M_HeatTime"))
        self.gridLayout.addWidget(self.lE_M_HeatTime, 1, 2, 1, 1)
        self.lE_T_MeasCurr = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_T_MeasCurr.setObjectName(_fromUtf8("lE_T_MeasCurr"))
        self.gridLayout.addWidget(self.lE_T_MeasCurr, 2, 3, 1, 1)
        self.lE_T_HeatTime = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_T_HeatTime.setObjectName(_fromUtf8("lE_T_HeatTime"))
        self.gridLayout.addWidget(self.lE_T_HeatTime, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(Dlg_Measurement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(Dlg_Measurement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Dlg_Measurement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.lE_M_WaitTime = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_M_WaitTime.setObjectName(_fromUtf8("lE_M_WaitTime"))
        self.gridLayout.addWidget(self.lE_M_WaitTime, 1, 5, 1, 1)
        self.lE_T_WaitTime = QtGui.QLineEdit(Dlg_Measurement)
        self.lE_T_WaitTime.setObjectName(_fromUtf8("lE_T_WaitTime"))
        self.gridLayout.addWidget(self.lE_T_WaitTime, 2, 5, 1, 1)
        self.label = QtGui.QLabel(Dlg_Measurement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dlg_Measurement)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dlg_Measurement)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dlg_Measurement.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dlg_Measurement.reject)
        QtCore.QMetaObject.connectSlotsByName(Dlg_Measurement)
        Dlg_Measurement.setTabOrder(self.lE_M_HeatCurr, self.lE_M_HeatTime)
        Dlg_Measurement.setTabOrder(self.lE_M_HeatTime, self.lE_M_MeasCurr)
        Dlg_Measurement.setTabOrder(self.lE_M_MeasCurr, self.lE_M_StabTime)
        Dlg_Measurement.setTabOrder(self.lE_M_StabTime, self.lE_M_WaitTime)
        Dlg_Measurement.setTabOrder(self.lE_M_WaitTime, self.lE_T_HeatCurr)
        Dlg_Measurement.setTabOrder(self.lE_T_HeatCurr, self.lE_T_HeatTime)
        Dlg_Measurement.setTabOrder(self.lE_T_HeatTime, self.lE_T_MeasCurr)
        Dlg_Measurement.setTabOrder(self.lE_T_MeasCurr, self.lE_T_StabTime)
        Dlg_Measurement.setTabOrder(self.lE_T_StabTime, self.lE_T_WaitTime)
        Dlg_Measurement.setTabOrder(self.lE_T_WaitTime, self.buttonBox)

    def retranslateUi(self, Dlg_Measurement):
        Dlg_Measurement.setWindowTitle(_translate("Dlg_Measurement", "Dialog", None))
        self.label_7.setText(_translate("Dlg_Measurement", "Transfer", None))
        self.label_6.setText(_translate("Dlg_Measurement", "Monitoring", None))
        self.label_3.setText(_translate("Dlg_Measurement", "Meas. current (A)", None))
        self.label_4.setText(_translate("Dlg_Measurement", "Stabilization time (s)", None))
        self.label_5.setText(_translate("Dlg_Measurement", "Wait time (min)", None))
        self.label_2.setText(_translate("Dlg_Measurement", "Heating time (s)", None))
        self.label.setText(_translate("Dlg_Measurement", "Heating current (A)", None))

